// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rhongomyniad.Domain.Context;

#nullable disable

namespace Rhongomyniad.Domain.Migrations
{
    [DbContext(typeof(RhongomyniadDbContext))]
    [Migration("20260222163044_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Rhongomyniad.Domain.Entities.LocalGame", b =>
                {
                    b.Property<long>("AppId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("app_id");

                    b.Property<string>("ConfigFilesDir")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_files_dir");

                    b.Property<string>("GameLauncher")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("game_launcher");

                    b.Property<string>("InstallDir")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("install_dir");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SaveFilesDir")
                        .HasColumnType("TEXT")
                        .HasColumnName("save_files_dir");

                    b.ToTable("local_games", (string)null);
                });

            modelBuilder.Entity("Rhongomyniad.Domain.Entities.SteamSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("install_path");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.PrimitiveCollection<string>("LibraryFolders")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("library_folders");

                    b.HasKey("Id");

                    b.ToTable("steam_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
